version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: debug_player
      POSTGRES_USER: debug_user
      POSTGRES_PASSWORD: debug_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U debug_user -d debug_player"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: .
    ports:
      - "5000:5000"
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://debug_user:debug_pass@postgres:5432/debug_player
      NODE_ENV: development
    volumes:
      - .:/app
      - /app/node_modules
      - /app/venv
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      bash -c "
        npm install --legacy-peer-deps &&
        python3.11 -m venv venv &&
        source venv/bin/activate &&
        pip install -r python_backend/requirements.txt &&
        npm run db:push &&
        npm run dev
      "

volumes:
  postgres_data: