name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  NODE_VERSION: '18'
  PYTHON_VERSION: '3.11'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          npm ci
          cd python_backend && pip install -r requirements.txt
      
      - name: Type check
        run: npm run check
      
      - name: Build
        run: npm run build
      
      - name: Unit tests
        run: npm run test:unit
      
      - name: Python backend tests
        run: |
          cd python_backend
          python test_backend.py
      
      - name: Install Playwright
        run: npx playwright install --with-deps chromium
      
      - name: Start server
        run: |
          npm run dev &
          sleep 10
          curl -I http://localhost:5000 || echo "Server not responding"
      
      - name: E2E tests
        run: npx playwright test --project=chromium
        env:
          CI: true
      
      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            test-results/
            playwright-report/